// <auto-generated />

using GlobalVariables;

namespace GlobalNamespace
{
	partial class Form1
	{
		/// <summary>
		/// Designer variable used to keep track of non-visual components.
		/// </summary>
		private System.ComponentModel.IContainer components = null;
		private System.Windows.Forms.Button btnSearch;
		private System.Windows.Forms.Button btnWrite;
		private System.Windows.Forms.RichTextBox rtbWriteLog;
		private System.Windows.Forms.TabControl tabControl2;
		private System.Windows.Forms.TabPage tabPage2;
		private System.Windows.Forms.TabPage tabPage3;
		private System.Windows.Forms.RichTextBox rtbErrorLog;
		private System.Windows.Forms.TabPage tabPage1;
		private System.Windows.Forms.RichTextBox rtbSearchLog;
		private System.Windows.Forms.Button btnAddFiles;
		private System.Windows.Forms.TabControl tabControl1;
		private System.Windows.Forms.TabPage tabPage4;
		private System.Windows.Forms.TabPage tabPage5;
		private System.Windows.Forms.ProgressBar fastProgressBar;
		private DataGridViewDoubleBuffered dataGridView1;
		private DataGridViewDoubleBuffered dataGridView2;
		private System.Windows.Forms.MenuStrip menuStrip1;
		private System.Windows.Forms.ToolStripMenuItem toolStripMenuItem1;
		private System.Windows.Forms.ToolStripMenuItem openFolderToolStripMenuItem;
		private System.Windows.Forms.ToolStripMenuItem optionsToolStripMenuItem;
		private System.Windows.Forms.ToolStripMenuItem openSettingsToolStripMenuItem;
		private System.Windows.Forms.ToolStripMenuItem exportTableToolStripMenuItem;
		private System.Windows.Forms.Button btnCancel;
		private System.Windows.Forms.ToolStripMenuItem clearResultsToolStripMenuItem;
		private System.Windows.Forms.ProgressBar slowProgressBar;
		private System.Windows.Forms.ContextMenuStrip PopupMenu;
		private System.Windows.Forms.ToolStripMenuItem removeLines;
		private System.Windows.Forms.ToolStripMenuItem showInExplorerToolStripMenuItem;

		/// <summary>
		/// Disposes resources used by the form.
		/// </summary>
		/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		protected override void Dispose(bool disposing)
		{
			if (disposing) {
				if (components != null) {
					components.Dispose();
				}
			}
			base.Dispose(disposing);
		}

		/// <summary>
		/// This method is required for Windows Forms designer support.
		/// Do not change the method contents inside the source code editor. The Forms designer might
		/// not be able to load this method if it was changed manually.
		/// </summary>
		private void InitializeComponent()
		{
			this.components = new System.ComponentModel.Container();
			System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
			System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
			System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle4 = new System.Windows.Forms.DataGridViewCellStyle();
			System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle5 = new System.Windows.Forms.DataGridViewCellStyle();
			System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
			System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle6 = new System.Windows.Forms.DataGridViewCellStyle();
			System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle7 = new System.Windows.Forms.DataGridViewCellStyle();
			System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle9 = new System.Windows.Forms.DataGridViewCellStyle();
			System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle10 = new System.Windows.Forms.DataGridViewCellStyle();
			System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle8 = new System.Windows.Forms.DataGridViewCellStyle();
			this.btnSearch = new System.Windows.Forms.Button();
			this.btnWrite = new System.Windows.Forms.Button();
			this.tabControl2 = new System.Windows.Forms.TabControl();
			this.tabPage1 = new System.Windows.Forms.TabPage();
			this.rtbSearchLog = new System.Windows.Forms.RichTextBox();
			this.tabPage2 = new System.Windows.Forms.TabPage();
			this.rtbWriteLog = new System.Windows.Forms.RichTextBox();
			this.tabPage3 = new System.Windows.Forms.TabPage();
			this.rtbErrorLog = new System.Windows.Forms.RichTextBox();
			this.btnAddFiles = new System.Windows.Forms.Button();
			this.tabControl1 = new System.Windows.Forms.TabControl();
			this.PopupMenu = new System.Windows.Forms.ContextMenuStrip(this.components);
			this.removeLines = new System.Windows.Forms.ToolStripMenuItem();
			this.showInExplorerToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
			this.tabPage4 = new System.Windows.Forms.TabPage();
			this.tabPage5 = new System.Windows.Forms.TabPage();
			this.fastProgressBar = new System.Windows.Forms.ProgressBar();
			this.menuStrip1 = new System.Windows.Forms.MenuStrip();
			this.toolStripMenuItem1 = new System.Windows.Forms.ToolStripMenuItem();
			this.openFolderToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
			this.clearResultsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
			this.optionsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
			this.openSettingsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
			this.exportTableToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
			this.importTableToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
			this.btnCancel = new System.Windows.Forms.Button();
			this.slowProgressBar = new System.Windows.Forms.ProgressBar();
			this.dataGridView1 = new DataGridViewDoubleBuffered();
			this.Column1 = new System.Windows.Forms.DataGridViewTextBoxColumn();
			this.filepath1 = new System.Windows.Forms.DataGridViewTextBoxColumn();
			this.artist1 = new System.Windows.Forms.DataGridViewTextBoxColumn();
			this.title1 = new System.Windows.Forms.DataGridViewTextBoxColumn();
			this.album1 = new System.Windows.Forms.DataGridViewTextBoxColumn();
			this.date1 = new System.Windows.Forms.DataGridViewTextBoxColumn();
			this.genre1 = new System.Windows.Forms.DataGridViewTextBoxColumn();
			this.disccount1 = new System.Windows.Forms.DataGridViewTextBoxColumn();
			this.discnumber1 = new System.Windows.Forms.DataGridViewTextBoxColumn();
			this.trackcount1 = new System.Windows.Forms.DataGridViewTextBoxColumn();
			this.tracknumber1 = new System.Windows.Forms.DataGridViewTextBoxColumn();
			this.lyrics1 = new System.Windows.Forms.DataGridViewTextBoxColumn();
			this.cover1 = new System.Windows.Forms.DataGridViewLinkColumn();
			this.isVirtualFile = new System.Windows.Forms.DataGridViewCheckBoxColumn();
			this.dataGridView2 = new DataGridViewDoubleBuffered();
			this.number2 = new System.Windows.Forms.DataGridViewTextBoxColumn();
			this.filepath2 = new System.Windows.Forms.DataGridViewTextBoxColumn();
			this.service2 = new System.Windows.Forms.DataGridViewTextBoxColumn();
			this.artist2 = new System.Windows.Forms.DataGridViewTextBoxColumn();
			this.title2 = new System.Windows.Forms.DataGridViewTextBoxColumn();
			this.album2 = new System.Windows.Forms.DataGridViewTextBoxColumn();
			this.date2 = new System.Windows.Forms.DataGridViewTextBoxColumn();
			this.genre2 = new System.Windows.Forms.DataGridViewTextBoxColumn();
			this.disccount2 = new System.Windows.Forms.DataGridViewTextBoxColumn();
			this.discnumber2 = new System.Windows.Forms.DataGridViewTextBoxColumn();
			this.trackcount2 = new System.Windows.Forms.DataGridViewTextBoxColumn();
			this.tracknumber2 = new System.Windows.Forms.DataGridViewTextBoxColumn();
			this.lyrics2 = new System.Windows.Forms.DataGridViewTextBoxColumn();
			this.cover2 = new System.Windows.Forms.DataGridViewLinkColumn();
			this.duration2 = new System.Windows.Forms.DataGridViewTextBoxColumn();
			this.durationTotal2 = new System.Windows.Forms.DataGridViewTextBoxColumn();
			this.albumhits = new System.Windows.Forms.DataGridViewTextBoxColumn();
			this.tabControl2.SuspendLayout();
			this.tabPage1.SuspendLayout();
			this.tabPage2.SuspendLayout();
			this.tabPage3.SuspendLayout();
			this.tabControl1.SuspendLayout();
			this.PopupMenu.SuspendLayout();
			this.tabPage4.SuspendLayout();
			this.tabPage5.SuspendLayout();
			this.menuStrip1.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.dataGridView1)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.dataGridView2)).BeginInit();
			this.SuspendLayout();
			// 
			// btnSearch
			// 
			this.btnSearch.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
			this.btnSearch.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
			this.btnSearch.Font = new System.Drawing.Font("Calibri", 14.25F);
			this.btnSearch.Location = new System.Drawing.Point(1477, 741);
			this.btnSearch.Name = "btnSearch";
			this.btnSearch.Size = new System.Drawing.Size(172, 44);
			this.btnSearch.TabIndex = 1;
			this.btnSearch.TabStop = false;
			this.btnSearch.Text = "Search tags";
			this.btnSearch.UseVisualStyleBackColor = true;
			this.btnSearch.Click += new System.EventHandler(this.Button_SearchClick);
			// 
			// btnWrite
			// 
			this.btnWrite.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
			this.btnWrite.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
			this.btnWrite.Font = new System.Drawing.Font("Calibri", 14.25F);
			this.btnWrite.Location = new System.Drawing.Point(1477, 787);
			this.btnWrite.Name = "btnWrite";
			this.btnWrite.Size = new System.Drawing.Size(172, 44);
			this.btnWrite.TabIndex = 2;
			this.btnWrite.TabStop = false;
			this.btnWrite.Text = "Write tags";
			this.btnWrite.UseVisualStyleBackColor = true;
			this.btnWrite.Click += new System.EventHandler(this.Button_WriteClick);
			// 
			// tabControl2
			// 
			this.tabControl2.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
			this.tabControl2.Controls.Add(this.tabPage1);
			this.tabControl2.Controls.Add(this.tabPage2);
			this.tabControl2.Controls.Add(this.tabPage3);
			this.tabControl2.Location = new System.Drawing.Point(5, 676);
			this.tabControl2.Multiline = true;
			this.tabControl2.Name = "tabControl2";
			this.tabControl2.SelectedIndex = 0;
			this.tabControl2.Size = new System.Drawing.Size(1468, 155);
			this.tabControl2.TabIndex = 3;
			this.tabControl2.TabStop = false;
			// 
			// tabPage1
			// 
			this.tabPage1.Controls.Add(this.rtbSearchLog);
			this.tabPage1.Location = new System.Drawing.Point(4, 22);
			this.tabPage1.Name = "tabPage1";
			this.tabPage1.Size = new System.Drawing.Size(1460, 129);
			this.tabPage1.TabIndex = 2;
			this.tabPage1.Text = "Search Log";
			this.tabPage1.UseVisualStyleBackColor = true;
			// 
			// rtbSearchLog
			// 
			this.rtbSearchLog.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
			this.rtbSearchLog.BackColor = System.Drawing.SystemColors.Window;
			this.rtbSearchLog.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this.rtbSearchLog.DetectUrls = false;
			this.rtbSearchLog.Font = new System.Drawing.Font("Consolas", 8.25F);
			this.rtbSearchLog.Location = new System.Drawing.Point(3, 3);
			this.rtbSearchLog.Name = "rtbSearchLog";
			this.rtbSearchLog.ReadOnly = true;
			this.rtbSearchLog.ScrollBars = System.Windows.Forms.RichTextBoxScrollBars.Vertical;
			this.rtbSearchLog.Size = new System.Drawing.Size(1454, 123);
			this.rtbSearchLog.TabIndex = 4;
			this.rtbSearchLog.TabStop = false;
			this.rtbSearchLog.Text = "";
			this.rtbSearchLog.WordWrap = false;
			// 
			// tabPage2
			// 
			this.tabPage2.Controls.Add(this.rtbWriteLog);
			this.tabPage2.Location = new System.Drawing.Point(4, 22);
			this.tabPage2.Name = "tabPage2";
			this.tabPage2.Padding = new System.Windows.Forms.Padding(3);
			this.tabPage2.Size = new System.Drawing.Size(1460, 129);
			this.tabPage2.TabIndex = 0;
			this.tabPage2.Text = "Write Log";
			this.tabPage2.UseVisualStyleBackColor = true;
			// 
			// rtbWriteLog
			// 
			this.rtbWriteLog.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
			this.rtbWriteLog.BackColor = System.Drawing.SystemColors.Window;
			this.rtbWriteLog.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this.rtbWriteLog.DetectUrls = false;
			this.rtbWriteLog.Font = new System.Drawing.Font("Consolas", 8.25F);
			this.rtbWriteLog.Location = new System.Drawing.Point(3, 3);
			this.rtbWriteLog.Name = "rtbWriteLog";
			this.rtbWriteLog.ReadOnly = true;
			this.rtbWriteLog.ScrollBars = System.Windows.Forms.RichTextBoxScrollBars.Vertical;
			this.rtbWriteLog.Size = new System.Drawing.Size(1454, 123);
			this.rtbWriteLog.TabIndex = 5;
			this.rtbWriteLog.TabStop = false;
			this.rtbWriteLog.Text = "";
			this.rtbWriteLog.WordWrap = false;
			this.rtbWriteLog.LinkClicked += new System.Windows.Forms.LinkClickedEventHandler(this.RichTextBox_LinkClicked);
			// 
			// tabPage3
			// 
			this.tabPage3.Controls.Add(this.rtbErrorLog);
			this.tabPage3.Location = new System.Drawing.Point(4, 22);
			this.tabPage3.Name = "tabPage3";
			this.tabPage3.Padding = new System.Windows.Forms.Padding(3);
			this.tabPage3.Size = new System.Drawing.Size(1460, 129);
			this.tabPage3.TabIndex = 1;
			this.tabPage3.Text = "Error Log";
			this.tabPage3.UseVisualStyleBackColor = true;
			// 
			// rtbErrorLog
			// 
			this.rtbErrorLog.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
			this.rtbErrorLog.BackColor = System.Drawing.SystemColors.Window;
			this.rtbErrorLog.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this.rtbErrorLog.Font = new System.Drawing.Font("Consolas", 8.25F);
			this.rtbErrorLog.Location = new System.Drawing.Point(3, 3);
			this.rtbErrorLog.Name = "rtbErrorLog";
			this.rtbErrorLog.ReadOnly = true;
			this.rtbErrorLog.Size = new System.Drawing.Size(1454, 123);
			this.rtbErrorLog.TabIndex = 6;
			this.rtbErrorLog.TabStop = false;
			this.rtbErrorLog.Text = "";
			this.rtbErrorLog.WordWrap = false;
			this.rtbErrorLog.LinkClicked += new System.Windows.Forms.LinkClickedEventHandler(this.RichTextBox_LinkClicked);
			// 
			// btnAddFiles
			// 
			this.btnAddFiles.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
			this.btnAddFiles.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
			this.btnAddFiles.Font = new System.Drawing.Font("Calibri", 14.25F);
			this.btnAddFiles.Location = new System.Drawing.Point(1477, 695);
			this.btnAddFiles.Name = "btnAddFiles";
			this.btnAddFiles.Size = new System.Drawing.Size(172, 44);
			this.btnAddFiles.TabIndex = 0;
			this.btnAddFiles.TabStop = false;
			this.btnAddFiles.Text = "Add files";
			this.btnAddFiles.UseVisualStyleBackColor = true;
			this.btnAddFiles.Click += new System.EventHandler(this.Button_AddFilesClick);
			// 
			// tabControl1
			// 
			this.tabControl1.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
			this.tabControl1.ContextMenuStrip = this.PopupMenu;
			this.tabControl1.Controls.Add(this.tabPage4);
			this.tabControl1.Controls.Add(this.tabPage5);
			this.tabControl1.Location = new System.Drawing.Point(5, 24);
			this.tabControl1.Margin = new System.Windows.Forms.Padding(0);
			this.tabControl1.Multiline = true;
			this.tabControl1.Name = "tabControl1";
			this.tabControl1.SelectedIndex = 0;
			this.tabControl1.Size = new System.Drawing.Size(1646, 641);
			this.tabControl1.TabIndex = 5;
			this.tabControl1.TabStop = false;
			this.tabControl1.SelectedIndexChanged += new System.EventHandler(this.TabControl_SelectedIndexChanged);
			// 
			// PopupMenu
			// 
			this.PopupMenu.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.removeLines,
            this.showInExplorerToolStripMenuItem});
			this.PopupMenu.Name = "PopupMenu";
			this.PopupMenu.Size = new System.Drawing.Size(162, 48);
			// 
			// removeLines
			// 
			this.removeLines.Name = "removeLines";
			this.removeLines.Size = new System.Drawing.Size(161, 22);
			this.removeLines.Text = "Remove";
			this.removeLines.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this.removeLines.ToolTipText = "Removes the selected lines";
			this.removeLines.Click += new System.EventHandler(this.Popup_RemoveClick);
			// 
			// showInExplorerToolStripMenuItem
			// 
			this.showInExplorerToolStripMenuItem.Name = "showInExplorerToolStripMenuItem";
			this.showInExplorerToolStripMenuItem.Size = new System.Drawing.Size(161, 22);
			this.showInExplorerToolStripMenuItem.Text = "Show in Explorer";
			this.showInExplorerToolStripMenuItem.Click += new System.EventHandler(this.Popup_ShowExplorerClick);
			// 
			// tabPage4
			// 
			this.tabPage4.Controls.Add(this.dataGridView1);
			this.tabPage4.Location = new System.Drawing.Point(4, 22);
			this.tabPage4.Margin = new System.Windows.Forms.Padding(0);
			this.tabPage4.Name = "tabPage4";
			this.tabPage4.Size = new System.Drawing.Size(1638, 615);
			this.tabPage4.TabIndex = 2;
			this.tabPage4.Text = "Input Files";
			this.tabPage4.UseVisualStyleBackColor = true;
			// 
			// tabPage5
			// 
			this.tabPage5.Controls.Add(this.dataGridView2);
			this.tabPage5.Location = new System.Drawing.Point(4, 22);
			this.tabPage5.Name = "tabPage5";
			this.tabPage5.Padding = new System.Windows.Forms.Padding(3);
			this.tabPage5.Size = new System.Drawing.Size(1638, 615);
			this.tabPage5.TabIndex = 0;
			this.tabPage5.Text = "Search Details";
			this.tabPage5.UseVisualStyleBackColor = true;
			// 
			// fastProgressBar
			// 
			this.fastProgressBar.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
			this.fastProgressBar.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(205)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
			this.fastProgressBar.Location = new System.Drawing.Point(213, 672);
			this.fastProgressBar.Margin = new System.Windows.Forms.Padding(0);
			this.fastProgressBar.Name = "fastProgressBar";
			this.fastProgressBar.Size = new System.Drawing.Size(1258, 10);
			this.fastProgressBar.Step = 1;
			this.fastProgressBar.Style = System.Windows.Forms.ProgressBarStyle.Continuous;
			this.fastProgressBar.TabIndex = 8;
			this.fastProgressBar.Visible = false;
			// 
			// menuStrip1
			// 
			this.menuStrip1.BackColor = System.Drawing.SystemColors.Control;
			this.menuStrip1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.toolStripMenuItem1,
            this.optionsToolStripMenuItem});
			this.menuStrip1.Location = new System.Drawing.Point(0, 0);
			this.menuStrip1.Name = "menuStrip1";
			this.menuStrip1.Size = new System.Drawing.Size(1656, 24);
			this.menuStrip1.TabIndex = 9;
			this.menuStrip1.Text = "menuStrip1";
			// 
			// toolStripMenuItem1
			// 
			this.toolStripMenuItem1.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.openFolderToolStripMenuItem,
            this.clearResultsToolStripMenuItem});
			this.toolStripMenuItem1.Name = "toolStripMenuItem1";
			this.toolStripMenuItem1.Size = new System.Drawing.Size(37, 20);
			this.toolStripMenuItem1.Text = "File";
			// 
			// openFolderToolStripMenuItem
			// 
			this.openFolderToolStripMenuItem.Name = "openFolderToolStripMenuItem";
			this.openFolderToolStripMenuItem.Size = new System.Drawing.Size(147, 22);
			this.openFolderToolStripMenuItem.Text = "Add Directory";
			this.openFolderToolStripMenuItem.Click += new System.EventHandler(this.MenuItemClick_AddFolder);
			// 
			// clearResultsToolStripMenuItem
			// 
			this.clearResultsToolStripMenuItem.Name = "clearResultsToolStripMenuItem";
			this.clearResultsToolStripMenuItem.Size = new System.Drawing.Size(147, 22);
			this.clearResultsToolStripMenuItem.Text = "Clear Tables";
			this.clearResultsToolStripMenuItem.Click += new System.EventHandler(this.MenuItemClick_ClearTables);
			// 
			// optionsToolStripMenuItem
			// 
			this.optionsToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.openSettingsToolStripMenuItem,
            this.exportTableToolStripMenuItem,
            this.importTableToolStripMenuItem});
			this.optionsToolStripMenuItem.Name = "optionsToolStripMenuItem";
			this.optionsToolStripMenuItem.Size = new System.Drawing.Size(47, 20);
			this.optionsToolStripMenuItem.Text = "Tools";
			// 
			// openSettingsToolStripMenuItem
			// 
			this.openSettingsToolStripMenuItem.Name = "openSettingsToolStripMenuItem";
			this.openSettingsToolStripMenuItem.Size = new System.Drawing.Size(142, 22);
			this.openSettingsToolStripMenuItem.Text = "User Settings";
			this.openSettingsToolStripMenuItem.Click += new System.EventHandler(this.MenuItemClick_OpenSettings);
			// 
			// exportTableToolStripMenuItem
			// 
			this.exportTableToolStripMenuItem.Name = "exportTableToolStripMenuItem";
			this.exportTableToolStripMenuItem.Size = new System.Drawing.Size(142, 22);
			this.exportTableToolStripMenuItem.Text = "Export Table";
			this.exportTableToolStripMenuItem.Click += new System.EventHandler(this.MenuItemClick_ExportTable);
			// 
			// importTableToolStripMenuItem
			// 
			this.importTableToolStripMenuItem.Name = "importTableToolStripMenuItem";
			this.importTableToolStripMenuItem.Size = new System.Drawing.Size(142, 22);
			this.importTableToolStripMenuItem.Text = "Import Table";
			this.importTableToolStripMenuItem.Click += new System.EventHandler(this.MenuItemClick_ImportTable);
			// 
			// btnCancel
			// 
			this.btnCancel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
			this.btnCancel.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
			this.btnCancel.Font = new System.Drawing.Font("Calibri", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			this.btnCancel.Location = new System.Drawing.Point(1477, 671);
			this.btnCancel.Margin = new System.Windows.Forms.Padding(0);
			this.btnCancel.Name = "btnCancel";
			this.btnCancel.Size = new System.Drawing.Size(172, 22);
			this.btnCancel.TabIndex = 10;
			this.btnCancel.TabStop = false;
			this.btnCancel.Text = "Cancel";
			this.btnCancel.UseVisualStyleBackColor = true;
			this.btnCancel.Visible = false;
			this.btnCancel.Click += new System.EventHandler(this.Button_CancelClick);
			// 
			// slowProgressBar
			// 
			this.slowProgressBar.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
			this.slowProgressBar.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(205)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
			this.slowProgressBar.Location = new System.Drawing.Point(213, 681);
			this.slowProgressBar.Margin = new System.Windows.Forms.Padding(0);
			this.slowProgressBar.Name = "slowProgressBar";
			this.slowProgressBar.Size = new System.Drawing.Size(1258, 10);
			this.slowProgressBar.Step = 1;
			this.slowProgressBar.Style = System.Windows.Forms.ProgressBarStyle.Continuous;
			this.slowProgressBar.TabIndex = 11;
			this.slowProgressBar.Visible = false;
			this.slowProgressBar.VisibleChanged += new System.EventHandler(this.SlowProgressBar_VisibleChanged);
			// 
			// dataGridView1
			// 
			this.dataGridView1.AllowUserToAddRows = false;
			this.dataGridView1.AllowUserToResizeRows = false;
			dataGridViewCellStyle1.BackColor = System.Drawing.Color.White;
			this.dataGridView1.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
			this.dataGridView1.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
			this.dataGridView1.BackgroundColor = System.Drawing.SystemColors.Window;
			this.dataGridView1.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this.dataGridView1.CausesValidation = false;
			this.dataGridView1.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleVertical;
			this.dataGridView1.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
			dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle2.BackColor = System.Drawing.SystemColors.Window;
			dataGridViewCellStyle2.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F);
			dataGridViewCellStyle2.ForeColor = System.Drawing.SystemColors.WindowText;
			dataGridViewCellStyle2.Padding = new System.Windows.Forms.Padding(0, 3, 0, 3);
			dataGridViewCellStyle2.SelectionBackColor = System.Drawing.SystemColors.Highlight;
			dataGridViewCellStyle2.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
			dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
			this.dataGridView1.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
			this.dataGridView1.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
			this.dataGridView1.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
            this.Column1,
            this.filepath1,
            this.artist1,
            this.title1,
            this.album1,
            this.date1,
            this.genre1,
            this.disccount1,
            this.discnumber1,
            this.trackcount1,
            this.tracknumber1,
            this.lyrics1,
            this.cover1,
            this.isVirtualFile});
			dataGridViewCellStyle4.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle4.BackColor = System.Drawing.SystemColors.Window;
			dataGridViewCellStyle4.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F);
			dataGridViewCellStyle4.ForeColor = System.Drawing.SystemColors.ControlText;
			dataGridViewCellStyle4.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(205)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
			dataGridViewCellStyle4.SelectionForeColor = System.Drawing.Color.Black;
			dataGridViewCellStyle4.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
			this.dataGridView1.DefaultCellStyle = dataGridViewCellStyle4;
			this.dataGridView1.GridColor = System.Drawing.SystemColors.ControlLight;
			this.dataGridView1.Location = new System.Drawing.Point(0, 0);
			this.dataGridView1.Name = "dataGridView1";
			this.dataGridView1.RowHeadersVisible = false;
			dataGridViewCellStyle5.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(244)))), ((int)(((byte)(244)))));
			this.dataGridView1.RowsDefaultCellStyle = dataGridViewCellStyle5;
			this.dataGridView1.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
			this.dataGridView1.Size = new System.Drawing.Size(1640, 615);
			this.dataGridView1.TabIndex = 8;
			this.dataGridView1.TabStop = false;
			this.dataGridView1.CellContentClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.DataGridView_CellContentClick);
			this.dataGridView1.CellDoubleClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.DataGridView_CellDoubleClick);
			this.dataGridView1.CellMouseDown += new System.Windows.Forms.DataGridViewCellMouseEventHandler(this.DataGridView_CellMouseDown);
			this.dataGridView1.CellMouseEnter += new System.Windows.Forms.DataGridViewCellEventHandler(this.DataGridView_CellMouseEnter);
			this.dataGridView1.CellMouseLeave += new System.Windows.Forms.DataGridViewCellEventHandler(this.DataGridView_CellMouseLeave);
			this.dataGridView1.CellPainting += new System.Windows.Forms.DataGridViewCellPaintingEventHandler(this.DataGridView_CellPainting);
			this.dataGridView1.RowLeave += new System.Windows.Forms.DataGridViewCellEventHandler(this.DataGridView_CellMouseLeave);
			this.dataGridView1.SortCompare += new System.Windows.Forms.DataGridViewSortCompareEventHandler(this.DataGridView_SortCompare);
			this.dataGridView1.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.DataGridView_KeyPress);
			// 
			// Column1
			// 
			this.Column1.HeaderText = "#";
			this.Column1.MinimumWidth = 25;
			this.Column1.Name = "Column1";
			this.Column1.ReadOnly = true;
			this.Column1.ToolTipText = "Number";
			this.Column1.Width = 25;
			// 
			// filepath1
			// 
			this.filepath1.HeaderText = "Filepath";
			this.filepath1.MinimumWidth = 25;
			this.filepath1.Name = "filepath1";
			this.filepath1.ReadOnly = true;
			this.filepath1.ToolTipText = "Filepath";
			this.filepath1.Width = 370;
			// 
			// artist1
			// 
			this.artist1.HeaderText = "Artist";
			this.artist1.MinimumWidth = 25;
			this.artist1.Name = "artist1";
			this.artist1.ReadOnly = true;
			this.artist1.ToolTipText = "Artist";
			// 
			// title1
			// 
			this.title1.HeaderText = "Title";
			this.title1.MinimumWidth = 25;
			this.title1.Name = "title1";
			this.title1.ReadOnly = true;
			this.title1.ToolTipText = "Title";
			// 
			// album1
			// 
			this.album1.HeaderText = "Album";
			this.album1.MinimumWidth = 25;
			this.album1.Name = "album1";
			this.album1.ReadOnly = true;
			this.album1.ToolTipText = "Album";
			// 
			// date1
			// 
			this.date1.HeaderText = "Date";
			this.date1.MinimumWidth = 25;
			this.date1.Name = "date1";
			this.date1.ReadOnly = true;
			this.date1.ToolTipText = "Date";
			// 
			// genre1
			// 
			this.genre1.HeaderText = "Genre";
			this.genre1.MinimumWidth = 25;
			this.genre1.Name = "genre1";
			this.genre1.ReadOnly = true;
			this.genre1.ToolTipText = "Genre";
			// 
			// disccount1
			// 
			this.disccount1.HeaderText = "Disc Count";
			this.disccount1.MinimumWidth = 25;
			this.disccount1.Name = "disccount1";
			this.disccount1.ReadOnly = true;
			this.disccount1.ToolTipText = "Disc Count";
			this.disccount1.Width = 30;
			// 
			// discnumber1
			// 
			this.discnumber1.HeaderText = "Disc Number";
			this.discnumber1.MinimumWidth = 25;
			this.discnumber1.Name = "discnumber1";
			this.discnumber1.ReadOnly = true;
			this.discnumber1.ToolTipText = "Disc Number";
			this.discnumber1.Width = 30;
			// 
			// trackcount1
			// 
			this.trackcount1.HeaderText = "Track Count";
			this.trackcount1.MinimumWidth = 25;
			this.trackcount1.Name = "trackcount1";
			this.trackcount1.ReadOnly = true;
			this.trackcount1.ToolTipText = "Track Count";
			this.trackcount1.Width = 30;
			// 
			// tracknumber1
			// 
			this.tracknumber1.HeaderText = "Track Number";
			this.tracknumber1.MinimumWidth = 25;
			this.tracknumber1.Name = "tracknumber1";
			this.tracknumber1.ReadOnly = true;
			this.tracknumber1.ToolTipText = "Track Number";
			this.tracknumber1.Width = 30;
			// 
			// lyrics1
			// 
			dataGridViewCellStyle3.Padding = new System.Windows.Forms.Padding(0, 3, 0, 3);
			dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
			this.lyrics1.DefaultCellStyle = dataGridViewCellStyle3;
			this.lyrics1.HeaderText = "Unsynced Lyrics";
			this.lyrics1.MinimumWidth = 25;
			this.lyrics1.Name = "lyrics1";
			this.lyrics1.ReadOnly = true;
			this.lyrics1.ToolTipText = "Unsynced Lyrics";
			this.lyrics1.Width = 200;
			// 
			// cover1
			// 
			this.cover1.ActiveLinkColor = System.Drawing.Color.Black;
			this.cover1.AutoSizeMode = System.Windows.Forms.DataGridViewAutoSizeColumnMode.Fill;
			this.cover1.HeaderText = "Cover";
			this.cover1.LinkBehavior = System.Windows.Forms.LinkBehavior.NeverUnderline;
			this.cover1.LinkColor = System.Drawing.Color.Black;
			this.cover1.MinimumWidth = 25;
			this.cover1.Name = "cover1";
			this.cover1.ReadOnly = true;
			this.cover1.SortMode = System.Windows.Forms.DataGridViewColumnSortMode.Automatic;
			this.cover1.ToolTipText = "Cover";
			this.cover1.VisitedLinkColor = System.Drawing.Color.Black;
			// 
			// isVirtualFile
			// 
			this.isVirtualFile.FalseValue = "false";
			this.isVirtualFile.HeaderText = "isVirtualFile";
			this.isVirtualFile.Name = "isVirtualFile";
			this.isVirtualFile.ReadOnly = true;
			this.isVirtualFile.Resizable = System.Windows.Forms.DataGridViewTriState.False;
			this.isVirtualFile.SortMode = System.Windows.Forms.DataGridViewColumnSortMode.Automatic;
			this.isVirtualFile.ToolTipText = "isVirtualFile";
			this.isVirtualFile.TrueValue = "true";
			this.isVirtualFile.Visible = false;
			this.isVirtualFile.Width = 25;
			// 
			// dataGridView2
			// 
			this.dataGridView2.AllowUserToAddRows = false;
			this.dataGridView2.AllowUserToResizeRows = false;
			dataGridViewCellStyle6.BackColor = System.Drawing.Color.White;
			this.dataGridView2.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle6;
			this.dataGridView2.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
			this.dataGridView2.BackgroundColor = System.Drawing.SystemColors.Window;
			this.dataGridView2.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this.dataGridView2.CausesValidation = false;
			this.dataGridView2.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleVertical;
			this.dataGridView2.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
			dataGridViewCellStyle7.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle7.BackColor = System.Drawing.SystemColors.Control;
			dataGridViewCellStyle7.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F);
			dataGridViewCellStyle7.ForeColor = System.Drawing.SystemColors.WindowText;
			dataGridViewCellStyle7.Padding = new System.Windows.Forms.Padding(0, 3, 0, 3);
			dataGridViewCellStyle7.SelectionBackColor = System.Drawing.SystemColors.Highlight;
			dataGridViewCellStyle7.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
			dataGridViewCellStyle7.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
			this.dataGridView2.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle7;
			this.dataGridView2.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
			this.dataGridView2.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
            this.number2,
            this.filepath2,
            this.service2,
            this.artist2,
            this.title2,
            this.album2,
            this.date2,
            this.genre2,
            this.disccount2,
            this.discnumber2,
            this.trackcount2,
            this.tracknumber2,
            this.lyrics2,
            this.cover2,
            this.duration2,
            this.durationTotal2,
            this.albumhits});
			dataGridViewCellStyle9.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle9.BackColor = System.Drawing.SystemColors.Window;
			dataGridViewCellStyle9.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F);
			dataGridViewCellStyle9.ForeColor = System.Drawing.SystemColors.ControlText;
			dataGridViewCellStyle9.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(205)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
			dataGridViewCellStyle9.SelectionForeColor = System.Drawing.Color.Black;
			dataGridViewCellStyle9.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
			this.dataGridView2.DefaultCellStyle = dataGridViewCellStyle9;
			this.dataGridView2.GridColor = System.Drawing.SystemColors.ControlLight;
			this.dataGridView2.Location = new System.Drawing.Point(0, 0);
			this.dataGridView2.Margin = new System.Windows.Forms.Padding(0);
			this.dataGridView2.Name = "dataGridView2";
			this.dataGridView2.RowHeadersVisible = false;
			dataGridViewCellStyle10.BackColor = System.Drawing.SystemColors.ButtonFace;
			this.dataGridView2.RowsDefaultCellStyle = dataGridViewCellStyle10;
			this.dataGridView2.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
			this.dataGridView2.Size = new System.Drawing.Size(1640, 615);
			this.dataGridView2.TabIndex = 9;
			this.dataGridView2.TabStop = false;
			this.dataGridView2.CellContentClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.DataGridView_CellContentClick);
			this.dataGridView2.CellDoubleClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.DataGridView_CellDoubleClick);
			this.dataGridView2.CellMouseDown += new System.Windows.Forms.DataGridViewCellMouseEventHandler(this.DataGridView_CellMouseDown);
			this.dataGridView2.CellMouseEnter += new System.Windows.Forms.DataGridViewCellEventHandler(this.DataGridView_CellMouseEnter);
			this.dataGridView2.CellMouseLeave += new System.Windows.Forms.DataGridViewCellEventHandler(this.DataGridView_CellMouseLeave);
			this.dataGridView2.CellPainting += new System.Windows.Forms.DataGridViewCellPaintingEventHandler(this.DataGridView_CellPainting);
			this.dataGridView2.RowLeave += new System.Windows.Forms.DataGridViewCellEventHandler(this.DataGridView_CellMouseLeave);
			this.dataGridView2.SortCompare += new System.Windows.Forms.DataGridViewSortCompareEventHandler(this.DataGridView_SortCompare);
			this.dataGridView2.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.DataGridView_KeyPress);
			// 
			// number2
			// 
			this.number2.AutoSizeMode = System.Windows.Forms.DataGridViewAutoSizeColumnMode.DisplayedCellsExceptHeader;
			this.number2.HeaderText = "#";
			this.number2.MinimumWidth = 25;
			this.number2.Name = "number2";
			this.number2.ReadOnly = true;
			this.number2.ToolTipText = "Number";
			this.number2.Width = 25;
			// 
			// filepath2
			// 
			this.filepath2.HeaderText = "Filepath";
			this.filepath2.MinimumWidth = 25;
			this.filepath2.Name = "filepath2";
			this.filepath2.ReadOnly = true;
			this.filepath2.ToolTipText = "Filepath";
			this.filepath2.Width = 300;
			// 
			// service2
			// 
			this.service2.HeaderText = "Service";
			this.service2.MinimumWidth = 25;
			this.service2.Name = "service2";
			this.service2.ReadOnly = true;
			this.service2.ToolTipText = "Service";
			this.service2.Width = 70;
			// 
			// artist2
			// 
			this.artist2.HeaderText = "Artist";
			this.artist2.MinimumWidth = 25;
			this.artist2.Name = "artist2";
			this.artist2.ReadOnly = true;
			this.artist2.ToolTipText = "Artist";
			// 
			// title2
			// 
			this.title2.HeaderText = "Title";
			this.title2.MinimumWidth = 25;
			this.title2.Name = "title2";
			this.title2.ReadOnly = true;
			this.title2.ToolTipText = "Title";
			// 
			// album2
			// 
			this.album2.HeaderText = "Album";
			this.album2.MinimumWidth = 25;
			this.album2.Name = "album2";
			this.album2.ReadOnly = true;
			this.album2.ToolTipText = "Album";
			// 
			// date2
			// 
			this.date2.HeaderText = "Date";
			this.date2.MinimumWidth = 25;
			this.date2.Name = "date2";
			this.date2.ReadOnly = true;
			this.date2.ToolTipText = "Date";
			// 
			// genre2
			// 
			this.genre2.HeaderText = "Genre";
			this.genre2.MinimumWidth = 25;
			this.genre2.Name = "genre2";
			this.genre2.ReadOnly = true;
			this.genre2.ToolTipText = "Genre";
			// 
			// disccount2
			// 
			this.disccount2.HeaderText = "Disc Count";
			this.disccount2.MinimumWidth = 25;
			this.disccount2.Name = "disccount2";
			this.disccount2.ReadOnly = true;
			this.disccount2.ToolTipText = "Disc Count";
			this.disccount2.Width = 30;
			// 
			// discnumber2
			// 
			this.discnumber2.HeaderText = "Disc Number";
			this.discnumber2.MinimumWidth = 25;
			this.discnumber2.Name = "discnumber2";
			this.discnumber2.ReadOnly = true;
			this.discnumber2.ToolTipText = "Disc Number";
			this.discnumber2.Width = 30;
			// 
			// trackcount2
			// 
			this.trackcount2.HeaderText = "Track Count";
			this.trackcount2.MinimumWidth = 25;
			this.trackcount2.Name = "trackcount2";
			this.trackcount2.ReadOnly = true;
			this.trackcount2.ToolTipText = "Track Count";
			this.trackcount2.Width = 30;
			// 
			// tracknumber2
			// 
			this.tracknumber2.HeaderText = "Track Number";
			this.tracknumber2.MinimumWidth = 25;
			this.tracknumber2.Name = "tracknumber2";
			this.tracknumber2.ReadOnly = true;
			this.tracknumber2.ToolTipText = "Track Number";
			this.tracknumber2.Width = 30;
			// 
			// lyrics2
			// 
			dataGridViewCellStyle8.Padding = new System.Windows.Forms.Padding(0, 5, 0, 0);
			dataGridViewCellStyle8.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
			this.lyrics2.DefaultCellStyle = dataGridViewCellStyle8;
			this.lyrics2.HeaderText = "Unsynced Lyrics";
			this.lyrics2.MinimumWidth = 25;
			this.lyrics2.Name = "lyrics2";
			this.lyrics2.ReadOnly = true;
			this.lyrics2.ToolTipText = "Unsynced Lyrics";
			this.lyrics2.Width = 200;
			// 
			// cover2
			// 
			this.cover2.ActiveLinkColor = System.Drawing.Color.Black;
			this.cover2.AutoSizeMode = System.Windows.Forms.DataGridViewAutoSizeColumnMode.Fill;
			this.cover2.HeaderText = "Cover";
			this.cover2.LinkBehavior = System.Windows.Forms.LinkBehavior.NeverUnderline;
			this.cover2.LinkColor = System.Drawing.Color.Black;
			this.cover2.MinimumWidth = 25;
			this.cover2.Name = "cover2";
			this.cover2.ReadOnly = true;
			this.cover2.SortMode = System.Windows.Forms.DataGridViewColumnSortMode.Automatic;
			this.cover2.ToolTipText = "Cover";
			this.cover2.VisitedLinkColor = System.Drawing.Color.Black;
			// 
			// duration2
			// 
			this.duration2.HeaderText = "Duration";
			this.duration2.MinimumWidth = 25;
			this.duration2.Name = "duration2";
			this.duration2.ReadOnly = true;
			this.duration2.ToolTipText = "Duration";
			this.duration2.Width = 30;
			// 
			// durationTotal2
			// 
			this.durationTotal2.HeaderText = "Duration total";
			this.durationTotal2.MinimumWidth = 25;
			this.durationTotal2.Name = "durationTotal2";
			this.durationTotal2.ReadOnly = true;
			this.durationTotal2.ToolTipText = "Duration total";
			this.durationTotal2.Width = 30;
			// 
			// albumhits
			// 
			this.albumhits.HeaderText = "Album Hits";
			this.albumhits.MinimumWidth = 25;
			this.albumhits.Name = "albumhits";
			this.albumhits.ReadOnly = true;
			this.albumhits.ToolTipText = "Album Hits";
			this.albumhits.Width = 30;
			// 
			// Form1
			// 
			this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.BackColor = System.Drawing.SystemColors.Control;
			this.ClientSize = new System.Drawing.Size(1656, 838);
			this.Controls.Add(this.slowProgressBar);
			this.Controls.Add(this.fastProgressBar);
			this.Controls.Add(this.btnCancel);
			this.Controls.Add(this.btnAddFiles);
			this.Controls.Add(this.btnWrite);
			this.Controls.Add(this.btnSearch);
			this.Controls.Add(this.menuStrip1);
			this.Controls.Add(this.tabControl1);
			this.Controls.Add(this.tabControl2);
			this.DoubleBuffered = true;
			this.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F);
			this.Icon = global::Shiny_ID3_Tagger.resources.icon_resources.icon_main;
			this.KeyPreview = true;
			this.MainMenuStrip = this.menuStrip1;
			this.MinimumSize = new System.Drawing.Size(500, 500);
			this.Name = "Form1";
			this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "Shiny ID3 Tagger";
			this.Load += new System.EventHandler(this.TabControl_SelectedIndexChanged);
			this.KeyDown += new System.Windows.Forms.KeyEventHandler(this.Form_KeyDown);
			this.tabControl2.ResumeLayout(false);
			this.tabPage1.ResumeLayout(false);
			this.tabPage2.ResumeLayout(false);
			this.tabPage3.ResumeLayout(false);
			this.tabControl1.ResumeLayout(false);
			this.PopupMenu.ResumeLayout(false);
			this.tabPage4.ResumeLayout(false);
			this.tabPage5.ResumeLayout(false);
			this.menuStrip1.ResumeLayout(false);
			this.menuStrip1.PerformLayout();
			((System.ComponentModel.ISupportInitialize)(this.dataGridView1)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.dataGridView2)).EndInit();
			this.ResumeLayout(false);
			this.PerformLayout();

		}
		private System.Windows.Forms.ToolStripMenuItem importTableToolStripMenuItem;
		private System.Windows.Forms.DataGridViewTextBoxColumn Column1;
		private System.Windows.Forms.DataGridViewTextBoxColumn filepath1;
		private System.Windows.Forms.DataGridViewTextBoxColumn artist1;
		private System.Windows.Forms.DataGridViewTextBoxColumn title1;
		private System.Windows.Forms.DataGridViewTextBoxColumn album1;
		private System.Windows.Forms.DataGridViewTextBoxColumn date1;
		private System.Windows.Forms.DataGridViewTextBoxColumn genre1;
		private System.Windows.Forms.DataGridViewTextBoxColumn disccount1;
		private System.Windows.Forms.DataGridViewTextBoxColumn discnumber1;
		private System.Windows.Forms.DataGridViewTextBoxColumn trackcount1;
		private System.Windows.Forms.DataGridViewTextBoxColumn tracknumber1;
		private System.Windows.Forms.DataGridViewTextBoxColumn lyrics1;
		private System.Windows.Forms.DataGridViewLinkColumn cover1;
		private System.Windows.Forms.DataGridViewCheckBoxColumn isVirtualFile;
		private System.Windows.Forms.DataGridViewTextBoxColumn number2;
		private System.Windows.Forms.DataGridViewTextBoxColumn filepath2;
		private System.Windows.Forms.DataGridViewTextBoxColumn service2;
		private System.Windows.Forms.DataGridViewTextBoxColumn artist2;
		private System.Windows.Forms.DataGridViewTextBoxColumn title2;
		private System.Windows.Forms.DataGridViewTextBoxColumn album2;
		private System.Windows.Forms.DataGridViewTextBoxColumn date2;
		private System.Windows.Forms.DataGridViewTextBoxColumn genre2;
		private System.Windows.Forms.DataGridViewTextBoxColumn disccount2;
		private System.Windows.Forms.DataGridViewTextBoxColumn discnumber2;
		private System.Windows.Forms.DataGridViewTextBoxColumn trackcount2;
		private System.Windows.Forms.DataGridViewTextBoxColumn tracknumber2;
		private System.Windows.Forms.DataGridViewTextBoxColumn lyrics2;
		private System.Windows.Forms.DataGridViewLinkColumn cover2;
		private System.Windows.Forms.DataGridViewTextBoxColumn duration2;
		private System.Windows.Forms.DataGridViewTextBoxColumn durationTotal2;
		private System.Windows.Forms.DataGridViewTextBoxColumn albumhits;
	}
}
